version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha4321
      MYSQL_DATABASE: api_product
      MYSQL_USER: adm-product
      MYSQL_PASSWORD: senha4321
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - "8080:8080"
